export const CHANGE_NEW_POST_TEXT = 'CHANGE_NEW_POST_TEXT';
export const ADD_POST = 'ADD_POST';

export const CHANGE_NEW_MESSAGE_TEXT = 'CHANGE_NEW_MESSAGE_TEXT';
export const ADD_MESSAGE = 'ADD_MESSAGE';
